In [1]:
import numpy as np

In [54]:
a=np.array([0,1,2,3,4,5,6,7,8])
a1=a.reshape(3,3)
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q2

In [9]:
a[np.where(a%2!=0)]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [ ]:
Q3

In [10]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

In [11]:
l=min(len(x),len(y))
l

10

In [13]:
a=[]
b=[]
for i in range(10):
    if(x[i]>y[i]):
        a.append(i)
    elif (x[i]==y[i]):
        b.append(i)
np.array(a)

array([1, 2, 4, 5, 6, 7, 8, 9])

In [14]:
np.array(b)

array([0])

Q3

In [22]:
a=np.arange(100).reshape(5,-1)

In [28]:
a[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [32]:
import random
a=[]
for i in range(10):
    a.append(random.randint(30,41))


In [33]:
np.array(a)

array([31, 36, 36, 30, 31, 37, 34, 40, 34, 33])

In [34]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
B=np.array([[7,8,10],[4,5,6],[1,2,3]])
B

array([[ 7,  8, 10],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [55]:
c=np.add(A,B)
c

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 12]])

In [40]:
e=np.subtract(A,B)
e

array([[-6, -6, -7],
       [ 0,  0,  0],
       [ 6,  6,  6]])

In [41]:
np.sum(A)

45

In [44]:
np.sum(B,axis=0)

array([12, 15, 19])

In [47]:
np.sum(c,axis=1)

array([31, 30, 30])

In [48]:
A@B

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 90, 114, 145]])

In [52]:
e=np.sort(c,axis=None).reshape(3,3)
e

array([[ 8,  8,  8],
       [10, 10, 10],
       [12, 12, 13]])

In [53]:
e.T

array([[ 8, 10, 12],
       [ 8, 10, 12],
       [ 8, 10, 13]])